on:
  push:
    branches:
      - version-1.1
  workflow_dispatch:

env:
  VPN_SERVER: ${{ secrets.VPN_SERVER }}
  VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
  VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Get list of modified files
        id: modified-files
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { files } } = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.sha
            });
            const fileNames = files.map(f => f.filename).join(' ');
            core.setOutput('files', fileNames);
      - name: Iterate and process each modified file via SSH
        run: |
          start_deploy="false"
          for file in ${{ steps.modified-files.outputs.files }}; do
              echo "Fue modificado $file"
              if [[ ! "$file" =~ ".yml" && ! "$file" =~ "Dockerfile" ]]; then
                echo "Dentro del IF"
                start_deploy="true"
              fi
          done
          echo "start_deploy<<EOF" >> $GITHUB_ENV
          echo "$start_deploy" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Install OpenConnect
        if: env.start_deploy == 'true'
        run: sudo apt-get update && sudo apt-get install -y openconnect

      - name: Connect to Cisco VPN
        if: env.start_deploy == 'true'
        run: |
          echo "$VPN_PASSWORD" | sudo openconnect \
            --protocol=anyconnect \
            --user=$VPN_USERNAME \
            --passwd-on-stdin \
            --servercert pin-sha256:NduQ2UphG38krSVOantp2M5C5rrF8naaxGdY/5JqZ3o= \
            --background \
            $VPN_SERVER

      - name: executing remote ssh commands using ssh key
        if: env.start_deploy == 'true'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          #key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd galileo-dev-v1.1/importador &&
            if [ ! -d "galileo_servicio_importador" ]; then
              echo "validada galileo-dev-v1.1/importador/galileo_servicio_importador" &&
              git clone https://github.com/apuenteCountigo/galileo_servicio_importador.git
            fi
            cd galileo_servicio_importador &&
            git fetch origin &&
            git checkout version-1.1 &&
            git reset --hard origin/version-1.1 &&
            git pull &&
            export PATH=/opt/maven/bin:$PATH && mvn clean install -DskipTests &&
            mv ./target/servicio-importador-0.0.1-SNAPSHOT.jar ../servicio-importador.jar &&
            cd ../../ &&
            CONTAINER_NAME="servicio-importador" &&
            IMAGE_NAME=$(docker inspect --format='{{.Config.Image}}' "$CONTAINER_NAME" 2>/dev/null) &&
            if [[ -n "$IMAGE_NAME" ]]; then
              docker stop "$CONTAINER_NAME" &&
              docker rm "$CONTAINER_NAME" &&
              docker rmi "$IMAGE_NAME" &&
              echo "$IMAGE_NAME"
            fi;
            docker compose up servicio-importador -d &&
            docker save -o /home/mome/galileo-images-v1.1/servicio-importador_1.1.6.tar.gz galileo/servicio-importador:1.1.6
            exit

      - name: Desconectar VPN
        if: always()
        run: |
          if [ -f /tmp/openconnect.pid ]; then
            sudo kill $(cat /tmp/openconnect.pid)
            sudo rm /tmp/openconnect.pid
          fi